### ISSUE TITLE
Error when reading JSON file

### ISSUE THREAD

**Issue by NeuroimagingOL** [hMRI-group/hMRI-toolbox#102]
Dear all,

I just started using the hMRI toolbox. I converted the DICOMS with the DICOM Import function implemented in SPM and the one implemented within the hMRI toolbox. However, in both cases, wenn I try to run the map creation there is an error that the json file cannot by read with. When I try to read it with get_metadata it says that the file is empty or corrupted.

I cannot find any differences in comparison to the example json-file downloadable from the website. I attached on of the json files I created with SPM here.

Can somebody find the error?
[sOL_3913-0015-00001-000224-01.json](https://github.com/user-attachments/files/17160711/sOL_3913-0015-00001-000224-01.json)

Best regards,
Tina

**Comment by lukeje** [comment]
I just opened the json file in vscode, and it is warning me that the `"ImplementationVersionName"` field contains an invalid character. Perhaps that is the source of the json reader not being able to read the file?

**Comment by NeuroimagingOL** [comment]
Thanks for you fast reply. You are right. The entry was 1.5.0/WIN32. It seems that the / is not working. When I replace it with \\ it works. 

Do you have an idea why this is happening? I assume I have to change that in every json file, or can that be avoided in the DICOM Import already?

**Comment by NeuroimagingOL** [comment]
I am using Windows. I just checked, the entry is already in the original DICOM header: ImplementationVersionName: '1.5.0/WIN32'

I just noticed that in all other fields where a / or \ occurs, it is a double \\, like here: "ImageType": "ORIGINAL\\PRIMARY\\M\\DIS2D".

I just see my previous answer was misleading, I changed it to \\, not to a single one as written above.

**Comment by lukeje** [comment]
I don't know; I would guess the problematic character is already in the DICOM. Using `\` instead of `/` will escape the problematic character, (you can already see in the json file that a literal `"\"` in a json string needs to be `"\\"`) but I don't think it is to do with linux vs. windows paths, but rather linux vs. windows character encoding. For now I would just recommend editing the files (this should be possible in an automated way using command line tools), but perhaps you could check whether the tool you use to export DICOMs is mangling this field somehow.

**Comment by NeuroimagingOL** [comment]
Dear all,

thanks for you help. I solved the problem with the following snipped:

jsonData = jsondecode(fileread('myjson.json')));
jsonData.acqpar.ImplementationVersionName = ['1.5.0\WIN32']; %here I changed the / to \
spm_jsonwrite('myjson,json',jsonData,struct('indent','     '));
