### ISSUE TITLE
Problem with B1 bias correction

### ISSUE THREAD

**Issue by Chia3744** [hMRI-group/hMRI-toolbox#37]
Dear all,

When I used ‘Create hMRI maps’ module, this warning insists -_’both RF sensitivity and B1 transmit bias corrections are required to generate a quantitative (calibrated) PD map. Either or both of these is missing. Therefore an amplitude "A" map will be output instead of a quantitative PD map. PD map calibration has been disabled’_ - and it leads to no PD map in the output folder. Based on my understanding, one can only provide RF sensitivity map for the UNICORT correction method and still get a PD map. Could anyone kindly advise me how to solve this problem?

The following details my settings ([hMRI_map_creation_logfile.log](https://github.com/hMRI-group/hMRI-toolbox/files/8130600/hMRI_map_creation_logfile.log)):
- SPM12: v7771   
- h MRI v0.2.4
- RF sensitivity bias correction: per contrast
- B1 bias correction: UNICORT
Processing parameters: Use metadata or standard defaults

Other information pop-up during running:
- No B1 map available. UNICORT will be applied
- B1 transmit field estimated using UNICORT and applied to correct R1 maps for B1 transmit bias.
- Averaged PDw/T1w/MTw will be calculated based on the first 8 echoes.
- Calculation of R1 and PD will use the small angle approximation.
- Imperfect spoiling correction is disabled. If your data were acquired with one of the standard MPM protocols (customized MT-FLASH sequence) for which the correction coefficients are available, it is recommended to enable that option.

Thanks,
Gary

**Comment by mfcallaghan** [comment]
Hi Gary,

Unified segmentation is the algorithm that underpins the UNICORT method, which approximates the transmit field (B1+) to correct R1 maps.  However, unified segmentation is also used to remove the receiver profile when computing PD maps.  This is the case even when you use the "Per Contrast" or "Single Contrast" options and supply calibration data to homogenise the receiver profile because some inhomogeneity will remain, even if that is the modulation of the body coil.

If UNICORT is required for R1 maps, the use of unified segmentation in this method would mean that the unified segmentation algorithm would be used twice with the same data.  It may be possible to do this, but it has not yet been validated and therefore is not available in the toolbox.  Instead, the PD calibration is disabled and only the signal amplitude, i.e. "A", is output - which is what you are seeing.

We hope this helps clarify things.  We will close the issue for now.

The hMRI Development Team
