### ISSUE TITLE
TotalReadoutTime and MixingTime

### ISSUE THREAD

**Issue by ins0mniac2** [hMRI-group/hMRI-toolbox#54]
I am working with data that came from the same Siemens system and using the same sequence as the example dataset in osf.io . One thing we noticed is that neither SPM nor dcm2niix (two converters we tried) extract these two parameters that are required by BIDS. Are there specific dicom tags to find these from ? Alternatively, how do I calculate these ?

**Comment by nbeliy** [comment]
These values are not stored by default in DICOM, the best way is to refer to the acquisition protocol.

For some sequences these values are stored in slightly hidden way dependent on sequence you use.
Check the `spm12/metadata/get_metadata_val_classic.m` in hmri toolbox.
For instance for mixing time (lines around 890) and sequence `b1epi4a3d2` it's second entry in `alFree` array. But it may strongly depend on sequence.

TRT can be calculated from echo spacing, as described in [bids docs](https://bids-specification.readthedocs.io/en/stable/glossary.html#objects.metadata.TotalReadoutTime). For effective echo spacing, refer to `get_metadata_val_classic.m`, it's also sequence dependent.

Last note, the needed metadata are stored in `MrPhoenixProtocol` field (or similar one, I don't remember the tag)  which is ignored by dicom2niix, but exported by spm.

Hope it helps,
Nikita

**Comment by lukeje** [comment]
Because of limitations from the sequence programming side, unfortunately in general it cannot be guaranteed that any of the fields required for 3D-EPI SE/STE B1 mapping (namely [FlipAngle, EchoTime, MixingTime and TotalReadoutTime](https://bids-specification.readthedocs.io/en/stable/appendices/qmri.html#tb1epi-specific-notes)) can be automatically extracted from the DICOM header.

As Nikita says, in the past attempts were made to store some of these parameters in an array of user variables ("free" fields) in the DICOM header, but historically the location of each parameter in this array has changed between versions of Siemens software and implementations by different pulse sequence programmers; there is an issue (#16) related to this. 

If you want the data to be BIDS-compatible, then I would recommend setting all of these parameters yourself for now based on the sequence protocol. I'm happy to give more input on this if you need help.

One more thing: please note that the 3D-EPI SE/STE B1-mapping code is not compatible with BIDS unless you make [a few changes.](https://github.com/hMRI-group/hMRI-toolbox/issues/46#issuecomment-1297192822)

**Comment by ins0mniac2** [comment]
Thank you both for responding. We do have the sequence pdf file -- can all four fields ([FlipAngle, EchoTime, MixingTime and TotalReadoutTime](https://bids-specification.readthedocs.io/en/stable/appendices/qmri.html#tb1epi-specific-notes)) be   retrieved from it ?

**Comment by ins0mniac2** [comment]
> These values are not stored by default in DICOM, the best way is to refer to the acquisition protocol.
> 
> For some sequences these values are stored in slightly hidden way dependent on sequence you use. Check the `spm12/metadata/get_metadata_val_classic.m` in hmri toolbox. For instance for mixing time (lines around 890) and sequence `b1epi4a3d2` it's second entry in `alFree` array. But it may strongly depend on sequence.
> 
> TRT can be calculated from echo spacing, as described in [bids docs](https://bids-specification.readthedocs.io/en/stable/glossary.html#objects.metadata.TotalReadoutTime). For effective echo spacing, refer to `get_metadata_val_classic.m`, it's also sequence dependent.
> 
> Last note, the needed metadata are stored in `MrPhoenixProtocol` field (or similar one, I don't remember the tag) which is ignored by dicom2niix, but exported by spm.
> 
> Hope it helps, Nikita

I am looking at `spm12/metadata/get_metadata_val_classic.m` at the case statement near line 890 as you suggest. Looking at the sidecar json file SPM produced, it seems our `SequenceName` is `seste1e3d2`, not quite `seste1d3d2`, but close!! The `alFree` array looks like this:
`[24,10,1000,2000,140,260,6,0,0,0,0,0,2,33800,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12345]`

I should mention that the 14th entry in the array rings a bell as the example dataset [here](https://osf.io/k4bs5/files/osfstorage) has `MixingTime=0.0338` . As I mentioned in the OP, I thought we were using the same sequence. While the `PulseSequenceDetails` matches with our data (both `mfc_seste_b1map_v1e` ) the `SequenceName` is slightly different.

**Comment by lukeje** [comment]
As Nikita suggested, that looks like the same format as @mfcallaghan's [seste1d3d2](https://github.com/hMRI-group/hMRI-toolbox/blob/1a142ef14d62d265f512bbd5c45a878f9bbab290/spm12/metadata/get_metadata_val_classic.m#L661-L662):
```matlab
% alFree: [VoxDeph,SpoilAmp,EddCurr0,EddCurr1,TRamp,TFlat,BWT,0,0,0,0,0,2,MixingTime,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12345],
% adFree: [0,0,0,0,0,0,0,SlabGradScale,RefocCorr,0,0,RFSpoilBasicIncr]
```

## Mixing time
You can see by comparing the definitions above and your array that the "MixingTime" is indeed 33800 µs.

## TotalReadoutTime
To explain how to derive the "TotalReadoutTime" I will assume that your protocol is the same as the one in the example dataset [here](https://owncloud.gwdg.de/index.php/s/iv2TOQwGy4FGDDZ). The echo spacing (which I think is also the ["EffectiveEchoSpacing"](https://bids-specification.readthedocs.io/en/stable/glossary.html#effectiveechospacing-metadata)) is `2*TRamp+TFlat = 540 µs`, with TRamp and TFlat taken from the above array. This is then multiplied by the number of measured phase encoding lines (48) divided by the phase encoding GRAPPA factor (2) to give `"TotalReadoutTime" = 540 µs * 24 = 12.96 ms`, which is the same as in the [BIDS MPM reference dataset](https://osf.io/k4bs5/) (after converting to seconds). Note that I am skipping over some inconsistencies in the competing definitions of "TotalReadoutTime" here (see #56 for more information). These fields cannot be filled automatically by tools such as [dcm2niix](https://github.com/rordenlab/dcm2niix) because the GRAPPA implementation in most (all?) implementations of the sequence is not the Siemens standard one, and so many DICOM fields are not filled.

## EchoTime
The "EchoTime" definitions should be good enough as long as the second TE in the protocol is longer than the first one. 

Note that the second (stimulated echo) TE being longer than the first (spin echo) TE is not guaranteed by many implementations, as these implementations do not use the second TE in any of the sequence timing calculations. I think the sequence used in the example dataset is one of these, as 130 ms does not correspond to any reasonable value I can think of for the stimulated echo TE (time since excitation, time since the spin-echo refocusing pulse, or time since the third stimulated-echo pulse). @mfcallaghan: is this the case, or did I miss anything?

## FlipAngle
In the DICOMs that I know about, the FlipAngle field is set to zero in the DICOMs. This is because of difficulties in assigning different flip angles to different images in a series. It's possible that a DICOM decorator could add this information as part of the reconstruction chain on the scanner, but that would require some effort from a pulse sequence programmer (@antoinelutti @kerrinpine  @mfcallaghan). For @mfcallaghan's implementation these are hard-coded and the same as those found in the [B1 defaults file](https://github.com/hMRI-group/hMRI-toolbox/blob/1a142ef14d62d265f512bbd5c45a878f9bbab290/config/hmri_b1_standard_defaults.m#L84).

**Comment by neurolabusc** [comment]
@lukeje can you provide a sample of some the Prisma data, either as a public dataset or by sharing them with my [institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php). The [sample code](https://github.com/hMRI-group/hMRI-toolbox/blob/1a142ef14d62d265f512bbd5c45a878f9bbab290/spm12/metadata/get_metadata_val_classic.m#L661-L662) suggests that for V* Siemens one can extract a lot from the CSA header for several of the sequences ('seste1d3d2', 'b1sev1a3d2' 'b1sev1b3d2' 'b1epi2f3d2' 'b1epi2g3d2' 'b1sev1a').

I am a strong advocate for having validation datasets like the [dcm_qa](https://github.com/neurolabusc/dcm_qa) series. This helps regression test code, allows others to replicate, provides a concrete example, and helps map Siemens classic CSA parameters from V* to their enhanced [XA](https://github.com/neurolabusc/dcm_qa_xa30) equivalents.

**Comment by neurolabusc** [comment]
@nbeliy as a correction, dcm2niix does not ignore MrPhoenixProtocol, but it does not transcribe it whole sale. Rather, it [converts](https://github.com/rordenlab/dcm2niix/blob/bb3a6c35d2bbac6ed95acb2cd0df65f35e79b5fb/console/nii_dicom_batch.cpp#L1599) documented sequence specific variable to their BIDS field. With documentation and examples, we can convert alFree and adFree tags directly to BIDS. A good role model would be BEP005 where validation datasets [dcm_qa_asl](https://github.com/neurolabusc/dcm_qa_asl) and [documentation](https://github.com/rordenlab/dcm2niix/tree/master/BIDS#manufacturer-siemens-arterial-spin-labeling) help map the CSA header to the BIDS values.

**Comment by lukeje** [comment]
@neurolabusc I didn't know that reading from the `alFree` and `adFree` fields could be supported in `dcm2niix`. Thanks for clarifying that and providing support.

> can you provide a sample of some the Prisma data, either as a public dataset or by sharing them with my [institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php).

Unfortunately I only have in vivo data from Martina Callaghan's implementations (`mfc_seste_b1map_v*`; the specific version that @ins0mniac2 is talking about). 

@mfcallaghan Would you or one of your group members have DICOMs from your sequences (`mfc_seste_b1map_v*`) measured on a phantom?

I will (at some point after the ISMRM abstract deadline) search through our database to see if we have some phantom data measured with implementations from @kerrinpine (`kp_seste_*`) or @antoinelutti (`al_B1mapping_*`), but Kerrin already told me that it is unlikely that he kept DICOMs from phantom testing of his new sequence versions. I can stick a phantom in to get data from the latest versions on each of the scanners at our institute. Older versions would be more of a problem.

@antoinelutti Would you or one of your group members have DICOMs from your sequences (`al_B1mapping_*`) measured on a phantom?

Regarding implementations on GE, Philips, etc. (mentioned [here](https://github.com/rordenlab/dcm2niix/issues/646#issuecomment-1307507820) but I'm answering here to keep this answer self-contained), to my knowledge this sequence was only ever implemented on Siemens systems, and implementations of the MPM protocol on scanners from other manufacturers used different B1 mapping methods (e.g. AFI).

**Comment by ins0mniac2** [comment]
Thank you so much @lukeje , @nbeliy , @neurolabusc . @lukeje : do you think it is safe to assume that for the purposes of extracting these two parameters, `seste1e3d2` and `seste1d3d2` are equivalent ?

**Comment by lukeje** [comment]
> do you think it is safe to assume that for the purposes of extracting these two parameters, `seste1e3d2` and `seste1d3d2` are equivalent?

Yes, I'm confident the arrangement of the parameters is the same between these two versions as the calculations come out as expected for the standard protocol.
